### ISSUE TITLE
[Bug]: Crash on Dedicated Servers

### ISSUE THREAD

**Issue by Darkosto** [cech12/ColorBlindness#6]
### Minecraft Version

1.18.2

### Forge Version

40.1.80

### Mod Version

0.2.0.1

### Modpack or other Mod

Modpack, further testing done with only forge+colorblindness

### Describe the Issue

Colorblindess causes a server crash during load citing client side code being called

### Logs

https://pastebin.com/xPDesc5f https://pastebin.com/xRCCDTUd

### Do you use any performance-enhancing mods (e.g. OptiFine)?

N/A

**Comment by cech12** [comment]
Thanks for your report, when I have time, I will look into the connected PR to fix it.

**Comment by Darkosto** [comment]
I tested out the PR on my server and everything looks to load up properly. Thanks for looking into it!

**Comment by cech12** [comment]
Really weird that this happens, because the client directory shouldn't be loaded on server side. I will look into that in some days :)

**Comment by cech12** [comment]
Thanks for your report. The PR is merged and will be release in mod version 0.2.0.2.
