### ISSUE TITLE
[Bug]: AMD driver not supported

### ISSUE THREAD

**Issue by Furrycalin** [cech12/ColorBlindness#9]
### Minecraft Version

1.18,2

### Forge Version

40.2.2

### Mod Version

1.0.0.0

### Describe the Issue

After loading Mod, use Lan Server Properties Mod（ https://www.curseforge.com/minecraft/mc-mods/lan-server-properties ）And use mapping software to map the port and let a friend connect. He enters the game and waits for a few seconds before the game crashes. The crash report shows that there is a problem with the graphics card driver. So I suspect that Mod does not support AMD graphics card drivers

### Do you use any performance-enhancing mods (e.g. OptiFine)?

None

**Comment by cech12** [comment]
@Furrycalin Could you add the crash logs to this issue? (pastebin link or something similar)

**Comment by cech12** [comment]
@Furrycalin Does the game crashes without ColorBlindness installed on both sides (server & client)?

**Comment by cech12** [comment]
@Furrycalin Please provide some more information. Otherwise the ticket will be closed on May 22nd.
